# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch: 
  push:
  # 当对分支main进行push操作的时候，这个工作流就被触发了
    branches: [ main ]
  pull_request:
  #只运行特定分支main
    branches: [ main ]
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30
    
env:
  bd_ikuuu: ${{ secrets.BD_IKUUU }}

permissions:
  contents: read

jobs:
  checkin:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test ikuuuSign.py
      run: |
        python src/ikuuuSign.py
